--[[
    Havoc Studios Bundler (Richie-Style)
--]]

local function start()
    local runEnv = (getfenv and getfenv()) or _G or shared;
    local hInit, hMod, hInst, hEnv;

    hInit, hMod, hInst, hEnv = (function()
--[[
    Havoc Studios Runtime Engine
    This was generated by /bundle.ts and is not meant to be modified.
]]

local instanceFromId, modules = {}, {}
local _G = (getfenv and getfenv()) or _G

local ROOT_PARENT = "ROOT"

local function resolveParent(parentId)
    if parentId == ROOT_PARENT then
        local Players = game:GetService("Players")
        return Players.LocalPlayer:WaitForChild("PlayerGui")
    end
    return instanceFromId[parentId]
end

-- Forward declare hEnv so TS.import and hMod can reference it
local hEnv

local TS = {
    import = function(self, s, ...)
        local args = {...}
        local last = s
        for i, v in ipairs(args) do
            if type(v) == "string" then
                last = last:FindFirstChild(v)
            else
                last = v
            end
        end

        -- Check bundled registry first before falling back to native require
        if modules[last] then
            local m = modules[last]
            if not m.loaded then
                m.loaded = true
                m.data = m.fn()(hEnv(last:GetFullName()))
            end
            return m.data
        end

        return require(last)
    end,

    getModule = function(self, s, ...)
        return _G.require(s)
    end
}

hEnv = function(id)
    local inst = instanceFromId[id]
    local env = setmetatable({
        script = inst,
        require = function(target)
            if modules[target] then
                local m = modules[target]
                if not m.loaded then
                    m.loaded = true
                    m.data = m.fn()(hEnv(target:GetFullName()))
                end
                return m.data
            end
            return require(target)
        end
    }, { __index = _G })
    _G[inst] = TS
    return env
end

local function hMod(name, class, id, parentId, fn)
    local inst = Instance.new(class)
    inst.Name = name
    inst.Parent = resolveParent(parentId)
    instanceFromId[id] = inst
    modules[inst] = { fn = fn, loaded = false }
end

local function hInst(name, class, id, parentId)
    local inst = Instance.new(class)
    inst.Name = name
    inst.Parent = resolveParent(parentId)
    instanceFromId[id] = inst
end

local function hInit()
    for inst, m in pairs(modules) do
        if inst:IsA("LocalScript") then
            task.spawn(function()
                setfenv(m.fn(), hEnv(inst:GetFullName()))()
            end)
        end
    end
end

return hInit, hMod, hInst, hEnv

    end)();

    hInst("Havoc", "Folder", "Havoc", "ROOT");
    hInst("Havoc", "Folder", "Havoc.Havoc", "Havoc");
    hInst("App", "ModuleScript", "Havoc.Havoc.App", "Havoc.Havoc");
    hInst("components", "Folder", "Havoc.Havoc.components", "Havoc.Havoc");
    hInst("Acrylic", "ModuleScript", "Havoc.Havoc.components.Acrylic", "Havoc.Havoc.components");
    hInst("Acrylic", "ModuleScript", "Havoc.Havoc.components.Acrylic.Acrylic", "Havoc.Havoc.components.Acrylic");
    hInst("Acrylic.story", "ModuleScript", "Havoc.Havoc.components.Acrylic.Acrylic.story", "Havoc.Havoc.components.Acrylic");
    hInst("acrylic-instance", "ModuleScript", "Havoc.Havoc.components.Acrylic.acrylic-instance", "Havoc.Havoc.components.Acrylic");
    hInst("ActionButton", "ModuleScript", "Havoc.Havoc.components.ActionButton", "Havoc.Havoc.components");
    hInst("Border", "ModuleScript", "Havoc.Havoc.components.Border", "Havoc.Havoc.components");
    hInst("BrightButton", "ModuleScript", "Havoc.Havoc.components.BrightButton", "Havoc.Havoc.components");
    hInst("BrightSlider", "ModuleScript", "Havoc.Havoc.components.BrightSlider", "Havoc.Havoc.components");
    hInst("Canvas", "ModuleScript", "Havoc.Havoc.components.Canvas", "Havoc.Havoc.components");
    hInst("Card", "ModuleScript", "Havoc.Havoc.components.Card", "Havoc.Havoc.components");
    hInst("Fill", "ModuleScript", "Havoc.Havoc.components.Fill", "Havoc.Havoc.components");
    hInst("Glow", "ModuleScript", "Havoc.Havoc.components.Glow", "Havoc.Havoc.components");
    hInst("ParallaxImage", "ModuleScript", "Havoc.Havoc.components.ParallaxImage", "Havoc.Havoc.components");
    hInst("constants", "ModuleScript", "Havoc.Havoc.constants", "Havoc.Havoc");
    hInst("context", "Folder", "Havoc.Havoc.context", "Havoc.Havoc");
    hInst("scale-context", "ModuleScript", "Havoc.Havoc.context.scale-context", "Havoc.Havoc.context");
    hInst("hooks", "Folder", "Havoc.Havoc.hooks", "Havoc.Havoc");
    hInst("common", "Folder", "Havoc.Havoc.hooks.common", "Havoc.Havoc.hooks");
    hInst("flipper-hooks", "ModuleScript", "Havoc.Havoc.hooks.common.flipper-hooks", "Havoc.Havoc.hooks.common");
    hInst("get-binding", "ModuleScript", "Havoc.Havoc.hooks.common.flipper-hooks.get-binding", "Havoc.Havoc.hooks.common.flipper-hooks");
    hInst("use-goal", "ModuleScript", "Havoc.Havoc.hooks.common.flipper-hooks.use-goal", "Havoc.Havoc.hooks.common.flipper-hooks");
    hInst("use-instant", "ModuleScript", "Havoc.Havoc.hooks.common.flipper-hooks.use-instant", "Havoc.Havoc.hooks.common.flipper-hooks");
    hInst("use-linear", "ModuleScript", "Havoc.Havoc.hooks.common.flipper-hooks.use-linear", "Havoc.Havoc.hooks.common.flipper-hooks");
    hInst("use-motor", "ModuleScript", "Havoc.Havoc.hooks.common.flipper-hooks.use-motor", "Havoc.Havoc.hooks.common.flipper-hooks");
    hInst("use-spring", "ModuleScript", "Havoc.Havoc.hooks.common.flipper-hooks.use-spring", "Havoc.Havoc.hooks.common.flipper-hooks");
    hInst("rodux-hooks", "ModuleScript", "Havoc.Havoc.hooks.common.rodux-hooks", "Havoc.Havoc.hooks.common");
    hInst("use-delayed-update", "ModuleScript", "Havoc.Havoc.hooks.common.use-delayed-update", "Havoc.Havoc.hooks.common");
    hInst("use-did-mount", "ModuleScript", "Havoc.Havoc.hooks.common.use-did-mount", "Havoc.Havoc.hooks.common");
    hInst("use-forced-update", "ModuleScript", "Havoc.Havoc.hooks.common.use-forced-update", "Havoc.Havoc.hooks.common");
    hInst("use-interval", "ModuleScript", "Havoc.Havoc.hooks.common.use-interval", "Havoc.Havoc.hooks.common");
    hInst("use-mouse-location", "ModuleScript", "Havoc.Havoc.hooks.common.use-mouse-location", "Havoc.Havoc.hooks.common");
    hInst("use-promise", "ModuleScript", "Havoc.Havoc.hooks.common.use-promise", "Havoc.Havoc.hooks.common");
    hInst("use-set-state", "ModuleScript", "Havoc.Havoc.hooks.common.use-set-state", "Havoc.Havoc.hooks.common");
    hInst("use-spring", "ModuleScript", "Havoc.Havoc.hooks.common.use-spring", "Havoc.Havoc.hooks.common");
    hInst("use-viewport-size", "ModuleScript", "Havoc.Havoc.hooks.common.use-viewport-size", "Havoc.Havoc.hooks.common");
    hInst("use-current-page", "ModuleScript", "Havoc.Havoc.hooks.use-current-page", "Havoc.Havoc.hooks");
    hInst("use-friends", "ModuleScript", "Havoc.Havoc.hooks.use-friends", "Havoc.Havoc.hooks");
    hInst("use-parallax-offset", "ModuleScript", "Havoc.Havoc.hooks.use-parallax-offset", "Havoc.Havoc.hooks");
    hInst("use-scale", "ModuleScript", "Havoc.Havoc.hooks.use-scale", "Havoc.Havoc.hooks");
    hInst("use-theme", "ModuleScript", "Havoc.Havoc.hooks.use-theme", "Havoc.Havoc.hooks");
    hInst("jobs", "ModuleScript", "Havoc.Havoc.jobs", "Havoc.Havoc");
    hInst("acrylic", "ModuleScript", "Havoc.Havoc.jobs.acrylic", "Havoc.Havoc.jobs");
    hInst("character", "Folder", "Havoc.Havoc.jobs.character", "Havoc.Havoc.jobs");
    hInst("flight", "ModuleScript", "Havoc.Havoc.jobs.character.flight", "Havoc.Havoc.jobs.character");
    hInst("ghost", "ModuleScript", "Havoc.Havoc.jobs.character.ghost", "Havoc.Havoc.jobs.character");
    hInst("godmode", "ModuleScript", "Havoc.Havoc.jobs.character.godmode", "Havoc.Havoc.jobs.character");
    hInst("humanoid", "ModuleScript", "Havoc.Havoc.jobs.character.humanoid", "Havoc.Havoc.jobs.character");
    hInst("refresh", "ModuleScript", "Havoc.Havoc.jobs.character.refresh", "Havoc.Havoc.jobs.character");
    hInst("freecam", "ModuleScript", "Havoc.Havoc.jobs.freecam", "Havoc.Havoc.jobs");
    hInst("helpers", "Folder", "Havoc.Havoc.jobs.helpers", "Havoc.Havoc.jobs");
    hInst("freecam", "ModuleScript", "Havoc.Havoc.jobs.helpers.freecam", "Havoc.Havoc.jobs.helpers");
    hInst("get-selected-player", "ModuleScript", "Havoc.Havoc.jobs.helpers.get-selected-player", "Havoc.Havoc.jobs.helpers");
    hInst("job-store", "ModuleScript", "Havoc.Havoc.jobs.helpers.job-store", "Havoc.Havoc.jobs.helpers");
    hInst("players", "Folder", "Havoc.Havoc.jobs.players", "Havoc.Havoc.jobs");
    hInst("facebang", "ModuleScript", "Havoc.Havoc.jobs.players.facebang", "Havoc.Havoc.jobs.players");
    hInst("hide", "ModuleScript", "Havoc.Havoc.jobs.players.hide", "Havoc.Havoc.jobs.players");
    hInst("kill", "ModuleScript", "Havoc.Havoc.jobs.players.kill", "Havoc.Havoc.jobs.players");
    hInst("spectate", "ModuleScript", "Havoc.Havoc.jobs.players.spectate", "Havoc.Havoc.jobs.players");
    hInst("teleport", "ModuleScript", "Havoc.Havoc.jobs.players.teleport", "Havoc.Havoc.jobs.players");
    hInst("server", "ModuleScript", "Havoc.Havoc.jobs.server", "Havoc.Havoc.jobs");
    hInst("main", "LocalScript", "Havoc.Havoc.main", "Havoc.Havoc");
    hInst("store", "Folder", "Havoc.Havoc.store", "Havoc.Havoc");
    hInst("actions", "Folder", "Havoc.Havoc.store.actions", "Havoc.Havoc.store");
    hInst("dashboard.action", "ModuleScript", "Havoc.Havoc.store.actions.dashboard.action", "Havoc.Havoc.store.actions");
    hInst("jobs.action", "ModuleScript", "Havoc.Havoc.store.actions.jobs.action", "Havoc.Havoc.store.actions");
    hInst("options.action", "ModuleScript", "Havoc.Havoc.store.actions.options.action", "Havoc.Havoc.store.actions");
    hInst("models", "Folder", "Havoc.Havoc.store.models", "Havoc.Havoc.store");
    hInst("dashboard.model", "ModuleScript", "Havoc.Havoc.store.models.dashboard.model", "Havoc.Havoc.store.models");
    hInst("jobs.model", "ModuleScript", "Havoc.Havoc.store.models.jobs.model", "Havoc.Havoc.store.models");
    hInst("options.model", "ModuleScript", "Havoc.Havoc.store.models.options.model", "Havoc.Havoc.store.models");
    hInst("persistent-state", "ModuleScript", "Havoc.Havoc.store.persistent-state", "Havoc.Havoc.store");
    hInst("reducers", "Folder", "Havoc.Havoc.store.reducers", "Havoc.Havoc.store");
    hInst("dashboard.reducer", "ModuleScript", "Havoc.Havoc.store.reducers.dashboard.reducer", "Havoc.Havoc.store.reducers");
    hInst("jobs.reducer", "ModuleScript", "Havoc.Havoc.store.reducers.jobs.reducer", "Havoc.Havoc.store.reducers");
    hInst("options.reducer", "ModuleScript", "Havoc.Havoc.store.reducers.options.reducer", "Havoc.Havoc.store.reducers");
    hInst("store", "ModuleScript", "Havoc.Havoc.store.store", "Havoc.Havoc.store");
    hInst("theme", "ModuleScript", "Havoc.Havoc.theme", "Havoc.Havoc");
    hInst("themes", "ModuleScript", "Havoc.Havoc.themes", "Havoc.Havoc");
    hInst("crimson", "ModuleScript", "Havoc.Havoc.themes.crimson", "Havoc.Havoc.themes");
    hInst("frosted-glass", "ModuleScript", "Havoc.Havoc.themes.frosted-glass", "Havoc.Havoc.themes");
    hInst("high-contrast", "ModuleScript", "Havoc.Havoc.themes.high-contrast", "Havoc.Havoc.themes");
    hInst("light-theme", "ModuleScript", "Havoc.Havoc.themes.light-theme", "Havoc.Havoc.themes");
    hInst("obsidian", "ModuleScript", "Havoc.Havoc.themes.obsidian", "Havoc.Havoc.themes");
    hInst("sorbet", "ModuleScript", "Havoc.Havoc.themes.sorbet", "Havoc.Havoc.themes");
    hInst("theme.interface", "ModuleScript", "Havoc.Havoc.themes.theme.interface", "Havoc.Havoc.themes");
    hInst("utils", "Folder", "Havoc.Havoc.utils", "Havoc.Havoc");
    hInst("array-util", "ModuleScript", "Havoc.Havoc.utils.array-util", "Havoc.Havoc.utils");
    hInst("binding-util", "ModuleScript", "Havoc.Havoc.utils.binding-util", "Havoc.Havoc.utils");
    hInst("color3", "ModuleScript", "Havoc.Havoc.utils.color3", "Havoc.Havoc.utils");
    hInst("debug", "ModuleScript", "Havoc.Havoc.utils.debug", "Havoc.Havoc.utils");
    hInst("http", "ModuleScript", "Havoc.Havoc.utils.http", "Havoc.Havoc.utils");
    hInst("number-util", "ModuleScript", "Havoc.Havoc.utils.number-util", "Havoc.Havoc.utils");
    hInst("timeout", "ModuleScript", "Havoc.Havoc.utils.timeout", "Havoc.Havoc.utils");
    hInst("udim2", "ModuleScript", "Havoc.Havoc.utils.udim2", "Havoc.Havoc.utils");
    hInst("views", "Folder", "Havoc.Havoc.views", "Havoc.Havoc");
    hInst("Clock", "ModuleScript", "Havoc.Havoc.views.Clock", "Havoc.Havoc.views");
    hInst("Clock", "ModuleScript", "Havoc.Havoc.views.Clock.Clock", "Havoc.Havoc.views.Clock");
    hInst("Dashboard", "ModuleScript", "Havoc.Havoc.views.Dashboard", "Havoc.Havoc.views");
    hInst("Dashboard", "ModuleScript", "Havoc.Havoc.views.Dashboard.Dashboard", "Havoc.Havoc.views.Dashboard");
    hInst("Dashboard.story", "ModuleScript", "Havoc.Havoc.views.Dashboard.Dashboard.story", "Havoc.Havoc.views.Dashboard");
    hInst("Hint", "ModuleScript", "Havoc.Havoc.views.Hint", "Havoc.Havoc.views");
    hInst("Hint", "ModuleScript", "Havoc.Havoc.views.Hint.Hint", "Havoc.Havoc.views.Hint");
    hInst("Navbar", "ModuleScript", "Havoc.Havoc.views.Navbar", "Havoc.Havoc.views");
    hInst("Navbar", "ModuleScript", "Havoc.Havoc.views.Navbar.Navbar", "Havoc.Havoc.views.Navbar");
    hInst("Navbar.story", "ModuleScript", "Havoc.Havoc.views.Navbar.Navbar.story", "Havoc.Havoc.views.Navbar");
    hInst("NavbarTab", "ModuleScript", "Havoc.Havoc.views.Navbar.NavbarTab", "Havoc.Havoc.views.Navbar");
    hInst("Pages", "ModuleScript", "Havoc.Havoc.views.Pages", "Havoc.Havoc.views");
    hInst("Apps", "ModuleScript", "Havoc.Havoc.views.Pages.Apps", "Havoc.Havoc.views.Pages");
    hInst("Apps", "ModuleScript", "Havoc.Havoc.views.Pages.Apps.Apps", "Havoc.Havoc.views.Pages.Apps");
    hInst("Players", "ModuleScript", "Havoc.Havoc.views.Pages.Apps.Players", "Havoc.Havoc.views.Pages.Apps");
    hInst("Actions", "ModuleScript", "Havoc.Havoc.views.Pages.Apps.Players.Actions", "Havoc.Havoc.views.Pages.Apps.Players");
    hInst("Avatar", "ModuleScript", "Havoc.Havoc.views.Pages.Apps.Players.Avatar", "Havoc.Havoc.views.Pages.Apps.Players");
    hInst("Players", "ModuleScript", "Havoc.Havoc.views.Pages.Apps.Players.Players", "Havoc.Havoc.views.Pages.Apps.Players");
    hInst("Selection", "ModuleScript", "Havoc.Havoc.views.Pages.Apps.Players.Selection", "Havoc.Havoc.views.Pages.Apps.Players");
    hInst("Username", "ModuleScript", "Havoc.Havoc.views.Pages.Apps.Players.Username", "Havoc.Havoc.views.Pages.Apps.Players");
    hInst("Home", "ModuleScript", "Havoc.Havoc.views.Pages.Home", "Havoc.Havoc.views.Pages");
    hInst("FriendActivity", "ModuleScript", "Havoc.Havoc.views.Pages.Home.FriendActivity", "Havoc.Havoc.views.Pages.Home");
    hInst("FriendActivity", "ModuleScript", "Havoc.Havoc.views.Pages.Home.FriendActivity.FriendActivity", "Havoc.Havoc.views.Pages.Home.FriendActivity");
    hInst("FriendItem", "ModuleScript", "Havoc.Havoc.views.Pages.Home.FriendActivity.FriendItem", "Havoc.Havoc.views.Pages.Home.FriendActivity");
    hInst("GameItem", "ModuleScript", "Havoc.Havoc.views.Pages.Home.FriendActivity.GameItem", "Havoc.Havoc.views.Pages.Home.FriendActivity");
    hInst("Home", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Home", "Havoc.Havoc.views.Pages.Home");
    hInst("Profile", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Profile", "Havoc.Havoc.views.Pages.Home");
    hInst("Actions", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Profile.Actions", "Havoc.Havoc.views.Pages.Home.Profile");
    hInst("Avatar", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Profile.Avatar", "Havoc.Havoc.views.Pages.Home.Profile");
    hInst("Info", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Profile.Info", "Havoc.Havoc.views.Pages.Home.Profile");
    hInst("Profile", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Profile.Profile", "Havoc.Havoc.views.Pages.Home.Profile");
    hInst("Sliders", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Profile.Sliders", "Havoc.Havoc.views.Pages.Home.Profile");
    hInst("Username", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Profile.Username", "Havoc.Havoc.views.Pages.Home.Profile");
    hInst("Server", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Server", "Havoc.Havoc.views.Pages.Home");
    hInst("Server", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Server.Server", "Havoc.Havoc.views.Pages.Home.Server");
    hInst("ServerAction", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Server.ServerAction", "Havoc.Havoc.views.Pages.Home.Server");
    hInst("StatusLabel", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Server.StatusLabel", "Havoc.Havoc.views.Pages.Home.Server");
    hInst("Title", "ModuleScript", "Havoc.Havoc.views.Pages.Home.Title", "Havoc.Havoc.views.Pages.Home");
    hInst("Misc", "ModuleScript", "Havoc.Havoc.views.Pages.Misc", "Havoc.Havoc.views.Pages");
    hInst("FacebangModal", "ModuleScript", "Havoc.Havoc.views.Pages.Misc.FacebangModal", "Havoc.Havoc.views.Pages.Misc");
    hInst("Misc", "ModuleScript", "Havoc.Havoc.views.Pages.Misc.Misc", "Havoc.Havoc.views.Pages.Misc");
    hInst("Options", "ModuleScript", "Havoc.Havoc.views.Pages.Options", "Havoc.Havoc.views.Pages");
    hInst("Config", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Config", "Havoc.Havoc.views.Pages.Options");
    hInst("Config", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Config.Config", "Havoc.Havoc.views.Pages.Options.Config");
    hInst("ConfigItem", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Config.ConfigItem", "Havoc.Havoc.views.Pages.Options.Config");
    hInst("Options", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Options", "Havoc.Havoc.views.Pages.Options");
    hInst("Shortcuts", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Shortcuts", "Havoc.Havoc.views.Pages.Options");
    hInst("ShortcutItem", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Shortcuts.ShortcutItem", "Havoc.Havoc.views.Pages.Options.Shortcuts");
    hInst("Shortcuts", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Shortcuts.Shortcuts", "Havoc.Havoc.views.Pages.Options.Shortcuts");
    hInst("Themes", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Themes", "Havoc.Havoc.views.Pages.Options");
    hInst("ThemeItem", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Themes.ThemeItem", "Havoc.Havoc.views.Pages.Options.Themes");
    hInst("Themes", "ModuleScript", "Havoc.Havoc.views.Pages.Options.Themes.Themes", "Havoc.Havoc.views.Pages.Options.Themes");
    hInst("Pages", "ModuleScript", "Havoc.Havoc.views.Pages.Pages", "Havoc.Havoc.views.Pages");
    hInst("Scripts", "ModuleScript", "Havoc.Havoc.views.Pages.Scripts", "Havoc.Havoc.views.Pages");
    hInst("Content", "ModuleScript", "Havoc.Havoc.views.Pages.Scripts.Content", "Havoc.Havoc.views.Pages.Scripts");
    hInst("ScriptCard", "ModuleScript", "Havoc.Havoc.views.Pages.Scripts.ScriptCard", "Havoc.Havoc.views.Pages.Scripts");
    hInst("Scripts", "ModuleScript", "Havoc.Havoc.views.Pages.Scripts.Scripts", "Havoc.Havoc.views.Pages.Scripts");
    hInst("constants", "ModuleScript", "Havoc.Havoc.views.Pages.Scripts.constants", "Havoc.Havoc.views.Pages.Scripts");
    hInst("include", "Folder", "Havoc.Havoc.include", "Havoc.Havoc");
    hInst("Promise", "ModuleScript", "Havoc.Havoc.include.Promise", "Havoc.Havoc.include");
    hInst("RuntimeLib", "ModuleScript", "Havoc.Havoc.include.RuntimeLib", "Havoc.Havoc.include");
    hInst("node_modules", "Folder", "Havoc.Havoc.include.node_modules", "Havoc.Havoc.include");
    hInst("compiler-types", "Folder", "Havoc.Havoc.include.node_modules.compiler-types", "Havoc.Havoc.include.node_modules");
    hInst("types", "Folder", "Havoc.Havoc.include.node_modules.compiler-types.types", "Havoc.Havoc.include.node_modules.compiler-types");
    hInst("exploit-types", "Folder", "Havoc.Havoc.include.node_modules.exploit-types", "Havoc.Havoc.include.node_modules");
    hInst("types", "Folder", "Havoc.Havoc.include.node_modules.exploit-types.types", "Havoc.Havoc.include.node_modules.exploit-types");
    hInst("flipper", "Folder", "Havoc.Havoc.include.node_modules.flipper", "Havoc.Havoc.include.node_modules");
    hInst("src", "ModuleScript", "Havoc.Havoc.include.node_modules.flipper.src", "Havoc.Havoc.include.node_modules.flipper");
    hInst("typings", "Folder", "Havoc.Havoc.include.node_modules.flipper.typings", "Havoc.Havoc.include.node_modules.flipper");
    hInst("make", "ModuleScript", "Havoc.Havoc.include.node_modules.make", "Havoc.Havoc.include.node_modules");
    hInst("node_modules", "Folder", "Havoc.Havoc.include.node_modules.make.node_modules", "Havoc.Havoc.include.node_modules.make");
    hInst("@rbxts", "Folder", "Havoc.Havoc.include.node_modules.make.node_modules.@rbxts", "Havoc.Havoc.include.node_modules.make.node_modules");
    hInst("compiler-types", "Folder", "Havoc.Havoc.include.node_modules.make.node_modules.@rbxts.compiler-types", "Havoc.Havoc.include.node_modules.make.node_modules.@rbxts");
    hInst("types", "Folder", "Havoc.Havoc.include.node_modules.make.node_modules.@rbxts.compiler-types.types", "Havoc.Havoc.include.node_modules.make.node_modules.@rbxts.compiler-types");
    hInst("object-utils", "ModuleScript", "Havoc.Havoc.include.node_modules.object-utils", "Havoc.Havoc.include.node_modules");
    hInst("roact", "Folder", "Havoc.Havoc.include.node_modules.roact", "Havoc.Havoc.include.node_modules");
    hInst("src", "ModuleScript", "Havoc.Havoc.include.node_modules.roact.src", "Havoc.Havoc.include.node_modules.roact");
    hInst("roact-hooked", "Folder", "Havoc.Havoc.include.node_modules.roact-hooked", "Havoc.Havoc.include.node_modules");
    hInst("out", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out", "Havoc.Havoc.include.node_modules.roact-hooked");
    hInst("hooks", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks", "Havoc.Havoc.include.node_modules.roact-hooked.out");
    hInst("use-binding", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-binding", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("use-callback", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-callback", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("use-context", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-context", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("use-effect", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-effect", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("use-memo", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-memo", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("use-mutable", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-mutable", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("use-reducer", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-reducer", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("use-ref", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-ref", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("use-state", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks.use-state", "Havoc.Havoc.include.node_modules.roact-hooked.out.hooks");
    hInst("types", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.types", "Havoc.Havoc.include.node_modules.roact-hooked.out");
    hInst("utils", "Folder", "Havoc.Havoc.include.node_modules.roact-hooked.out.utils", "Havoc.Havoc.include.node_modules.roact-hooked.out");
    hInst("are-deps-equal", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.utils.are-deps-equal", "Havoc.Havoc.include.node_modules.roact-hooked.out.utils");
    hInst("memoized-hook", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.utils.memoized-hook", "Havoc.Havoc.include.node_modules.roact-hooked.out.utils");
    hInst("with-hooks", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.with-hooks", "Havoc.Havoc.include.node_modules.roact-hooked.out");
    hInst("component-with-hooks", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.with-hooks.component-with-hooks", "Havoc.Havoc.include.node_modules.roact-hooked.out.with-hooks");
    hInst("with-hooks", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-hooked.out.with-hooks.with-hooks", "Havoc.Havoc.include.node_modules.roact-hooked.out.with-hooks");
    hInst("roact-rodux-hooked", "Folder", "Havoc.Havoc.include.node_modules.roact-rodux-hooked", "Havoc.Havoc.include.node_modules");
    hInst("out", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out", "Havoc.Havoc.include.node_modules.roact-rodux-hooked");
    hInst("components", "Folder", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.components", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out");
    hInst("context", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.components.context", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.components");
    hInst("provider", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.components.provider", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.components");
    hInst("helpers", "Folder", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.helpers", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out");
    hInst("shallow-equal", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.helpers.shallow-equal", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.helpers");
    hInst("hooks", "Folder", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.hooks", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out");
    hInst("use-dispatch", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.hooks.use-dispatch", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.hooks");
    hInst("use-selector", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.hooks.use-selector", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.hooks");
    hInst("use-store", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.hooks.use-store", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.hooks");
    hInst("types", "ModuleScript", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out.types", "Havoc.Havoc.include.node_modules.roact-rodux-hooked.out");
    hInst("rodux", "Folder", "Havoc.Havoc.include.node_modules.rodux", "Havoc.Havoc.include.node_modules");
    hInst("src", "ModuleScript", "Havoc.Havoc.include.node_modules.rodux.src", "Havoc.Havoc.include.node_modules.rodux");
    hInst("services", "ModuleScript", "Havoc.Havoc.include.node_modules.services", "Havoc.Havoc.include.node_modules");
    hInst("types", "Folder", "Havoc.Havoc.include.node_modules.types", "Havoc.Havoc.include.node_modules");
    hInst("include", "Folder", "Havoc.Havoc.include.node_modules.types.include", "Havoc.Havoc.include.node_modules.types");
    hInst("generated", "Folder", "Havoc.Havoc.include.node_modules.types.include.generated", "Havoc.Havoc.include.node_modules.types.include");

    hInit();
end

start();