--[[
    ci/bundle.lua
    Havoc Build System — Remodel bundler.
    Reads Havoc.rbxm, walks the full instance tree including node_modules,
    and emits a self-contained latest.lua with runtime + all module sources.

    Usage (via Remodel):
        remodel run ci/bundle.lua
        remodel run ci/bundle.lua MyModel.rbxm output.lua
--]]

local args        = arg or {...} or {}
local input_file  = args[1] or "Havoc.rbxm"
local output_file = args[2] or "latest.lua"

print("------------------------------------------")
print("[Havoc] Build System Initialized")
print("[Havoc] Input:  " .. input_file)
print("[Havoc] Output: " .. output_file)

-- ─── Load Model ───────────────────────────────────────────────────────────────

local model_data = remodel.readModelFile(input_file)
if not model_data or #model_data == 0 then
    error("[Havoc] Model file invalid or empty: " .. input_file)
end
local model = model_data[1]

-- ─── Open Output File ─────────────────────────────────────────────────────────

local file, openErr = io.open(output_file, "w")
if not file then
    error("[Havoc] Cannot open output file: " .. tostring(openErr))
end

local scriptCount   = 0
local missingCount  = 0

-- ─── Path Resolver ────────────────────────────────────────────────────────────
-- Walks up the instance tree collecting names until the model root,
-- producing e.g. {"include","node_modules","@rbxts","roact"} for a nested pkg.

local function getRelParts(inst)
    local parts = {}
    local curr  = inst
    while curr and curr.Name ~= model.Name do
        table.insert(parts, 1, curr.Name)
        curr = curr.Parent
    end
    return parts
end

-- ─── Source Finder ────────────────────────────────────────────────────────────
-- Probe order:
--   1. out/          — compiled TS app code
--   2. include/      — roblox-ts runtime shims (RuntimeLib, Promise, etc.)
--   3. node_modules/@rbxts/<pkg>/  — 4 common layouts per package

local function readSource(inst)
    local parts   = getRelParts(inst)
    local relPath = table.concat(parts, "/")

    -- Strip leading path prefixes so the probes below work regardless of
    -- where the instance sits in the tree
    local cleanRel = relPath:gsub("^include/", ""):gsub("^node_modules/", "")
    local pkgName  = parts[#parts]  -- last segment = the package or file name

    local attempts = {
        -- ── App source (roblox-ts out/ output) ──────────────────────────────
        "out/" .. relPath .. ".lua",
        "out/" .. relPath .. "/init.lua",
        "out/" .. relPath .. ".client.lua",
        -- ── roblox-ts include/ shims ─────────────────────────────────────────
        "include/" .. cleanRel .. ".lua",
        "include/" .. cleanRel .. "/init.lua",
        -- ── @rbxts node_modules — 4 common compiled layouts ──────────────────
        -- (src/ = roact/rodux, lib/ = flipper, out/ = roact-hooked, root = services/make)
        "node_modules/@rbxts/" .. pkgName .. "/src/init.lua",
        "node_modules/@rbxts/" .. pkgName .. "/lib/init.lua",
        "node_modules/@rbxts/" .. pkgName .. "/out/init.lua",
        "node_modules/@rbxts/" .. pkgName .. "/init.lua",
        -- ── Flat node_modules fallback (rare but exists in some forks) ────────
        "node_modules/" .. cleanRel .. ".lua",
        "node_modules/" .. cleanRel .. "/init.lua",
    }

    for _, loc in ipairs(attempts) do
        local ok, content = pcall(remodel.readFile, loc)
        if ok and content and #content > 0 then
            return content, loc
        end
    end

    return nil, nil
end

-- ─── Comment Stripper ─────────────────────────────────────────────────────────
-- Two-pass: block comments first (preserving newlines for stack trace accuracy),
-- then single-line comments.
-- Does NOT strip shebangs or copyright headers (not present in compiled TS output).

local function stripComments(src)
    -- Pass 1: --[[ ... ]] — replace body chars with nothing but keep newlines
    local result = src:gsub("%-%-%[%[(.-)%]%]", function(inner)
        return (inner:gsub("[^\n]", ""))
    end)
    -- Pass 2: -- single line comments
    result = result:gsub("%-%-[^\n]*", "")
    return result
end

-- ─── Bundle Header ────────────────────────────────────────────────────────────

file:write("-- Havoc | Auto-generated by ci/bundle.lua — do not edit\n")
file:write("local function start()\n")
file:write("    local hInit, hMod, hInst, hEnv = (function()\n")
file:write(remodel.readFile("ci/runtime.lua"))
file:write("\n    end)()\n\n")

-- ─── Walker ───────────────────────────────────────────────────────────────────
-- Recurses the ENTIRE tree including node_modules.
-- Folders and non-script instances → hInst (virtual instance, no source)
-- Scripts with found source       → hMod  (virtual module with factory fn)
-- Scripts with missing source     → hInst + warning (keeps tree intact)

local function walk(parent)
    for _, object in ipairs(parent:GetChildren()) do
        local name  = string.format("%q", object.Name)
        local id    = string.format("%q", object:GetFullName())
        local pId   = string.format("%q", parent:GetFullName())
        local class = object.ClassName
        local isScript = (class == "ModuleScript" or class == "LocalScript")

        if isScript then
            local source, foundAt = readSource(object)

            if source then
                scriptCount = scriptCount + 1
                local clean = stripComments(source)
                file:write(string.format(
                    "    hMod(%s, %q, %s, %s, function()\n",
                    name, class, id, pId
                ))
                file:write(
                    "        return setfenv(function(...)\n"
                    .. clean
                    .. "\n        end, hEnv(" .. id .. "))()\n"
                )
                file:write("    end)\n")
            else
                -- Source missing: register as a plain instance so the tree stays
                -- consistent and script.Parent chains don't break for other modules.
                missingCount = missingCount + 1
                print(string.format(
                    "[Havoc] WARNING: no source for %s (%s) — registered as plain instance",
                    object:GetFullName(), class
                ))
                file:write(string.format(
                    "    hInst(%s, %q, %s, %s)\n",
                    name, class, id, pId
                ))
            end
        else
            -- Folder, RemoteEvent, BindableEvent, etc.
            file:write(string.format(
                "    hInst(%s, %q, %s, %s)\n",
                name, class, id, pId
            ))
        end

        -- Always recurse — this is what registers @rbxts package children
        walk(object)
    end
end

-- Register model root as a Folder with nil parent (it has no parent in the executor)
file:write(string.format(
    "    hInst(%q, \"Folder\", %q, nil)\n",
    model.Name,
    model:GetFullName()
))

walk(model)

-- ─── Footer ───────────────────────────────────────────────────────────────────

file:write("\n    hInit()\nend\nstart()\n")
file:close()

print(string.format(
    "[Havoc] Build complete — %d scripts bundled, %d missing sources.",
    scriptCount, missingCount
))
print("------------------------------------------")

-- NOTE: No `return` here. bundle.lua is a Remodel build script, not a module.
-- hInit/hMod/hInst/hEnv exist only inside the generated latest.lua, not here.
