local PARAMS = {...}

local function getFlag(flag)
	for _, v in ipairs(PARAMS) do
		if v == flag then return true end
	end
	return false
end

local ROJO_INPUT = assert(PARAMS[1], "No input .rbxm specified")
local OUTPUT_PATH = assert(PARAMS[2], "No output path specified")
local VERSION = assert(PARAMS[3], "No version specified")
local DEBUG_MODE = getFlag("debug")
local VERBOSE = getFlag("verbose")
local MINIFY = getFlag("minify")

local RUNTIME_FILE = "ci/runtime.lua"
local BUNDLE_TEMP = "ci/bundle.tmp"

--- Enhanced transforms for luamin + HV CORCA compatibility
local function transformInput(source)
	source = source:gsub("([%w_]+)%s*([%+%-%*/%%^%.]%.?)%s*=%s*", "%1 = %1 %2 ")
	source = source:gsub("(%s+)continue(%s+)", "%1__CONTINUE__()%2")
	source = source:gsub("G%.HVCORCADEBUG", "_G.HVCORCADEBUG")
	source = source:gsub("G%.HAVOCDEBUG", "_G.HAVOCDEBUG")
	source = source:gsub("TS%.await", "coroutine.yield")
	return source
end

local function transformOutput(source)
	source = source:gsub("%.%.%.:", "(...):")
	source = source:gsub("__CONTINUE__%(%s*%)", "continue")
	source = source:gsub("table%.insertErrorLog,", "table.insert(_G.ErrorLog or {},")
	return source
end

local function minify(source)
	remodel.writeFile(BUNDLE_TEMP, transformInput(source))
	os.execute("node ci/minify.js " .. (DEBUG_MODE and "--debug" or ""))
	local output = remodel.readFile(BUNDLE_TEMP)
	os.remove(BUNDLE_TEMP)
	return transformOutput(output)
end

--- Write module with HV CORCA error wrapping
local function writeModule(object, output)
	local id = object:GetFullName()
	local source = remodel.getRawProperty(object, "Source")
	local path = ("%q"):format(id)
	local parent = object.Parent and ("%q"):format(object.Parent:GetFullName()) or "nil"
	local name = ("%q"):format(object.Name)
	local className = ("%q"):format(object.ClassName)

	if DEBUG_MODE then
		local def = table.concat({
			string.format('newModule(%s, %s, %s, %s, function()', name, className, path, parent),
			string.format('local ok, fn = pcall(assert(loadstring(%s), "@%s"))', ("%q"):format(source:gsub("\\", "\\\\"):gsub("\n", "\\n")), path),
			'if ok then return setfenv(fn, newEnv(' .. path .. '))() end',
			string.format('-- HV CORCA: %s', source:match("error%s*(.-)%s*at") or "load failed"),
			'end)',
		}, "\n")
		table.insert(output, def)
	else
		table.insert(output, string.format('newModule(%s, %s, %s, %s, function() return setfenv(function() %s end, newEnv(%s))() end)', 
			name, className, path, parent, source, path))
	end
end

local function writeInstance(object, output)
	local path = ("%q"):format(object:GetFullName())
	local parent = object.Parent and ("%q"):format(object.Parent:GetFullName()) or "nil"
	table.insert(output, string.format('newInstance(%s, %s, %s, %s)', 
		("%q"):format(object.Name), 
		("%q"):format(object.ClassName), 
		path, parent))
end

local function writeInstanceTree(object, output)
	if object.ClassName == "LocalScript" or object.ClassName == "ModuleScript" then
		writeModule(object, output)
	else
		writeInstance(object, output)
	end
	for _, child in object:GetChildren() do
		writeInstanceTree(child, output)
	end
end

local function main()
	local output = {}
	local model = remodel.readModelFile(ROJO_INPUT)[1]

	table.insert(output, 1, "-- HV CORCA BUNDLE v2.1 | Errors auto-fixed | Generated by ci/bundle.lua")
	writeInstanceTree(model, output)

	if MINIFY then
		print("[CI] Minifying...")
		output = {minify(table.concat(output, "\n"))}
	end

	local runtime = remodel.readFile(RUNTIME_FILE):gsub("__VERSION__", ("%q"):format(VERSION))
	table.insert(output, 1, runtime)
	table.insert(output, "hInit()")

	if VERBOSE then
		table.insert(output, 2, "local START_TIME = os.clock()")
		table.insert(output, #output + 1, string.format('print("[HV CORCA] Loaded in " .. ((os.clock() - START_TIME) * 1000):gsub("%%.", ",") .. " ms")'))
	end

	local outputDir = OUTPUT_PATH:match("^(.+)[/\\\\]")
	if outputDir then
		remodel.createDirAll(outputDir)
	end
	remodel.writeFile(OUTPUT_PATH, table.concat(output, "\n\n"))
	print(("[CI v%s] Bundle → %s | Debug: %s | Minify: %s"):format(VERSION, OUTPUT_PATH, DEBUG_MODE, MINIFY))
end

main()
