--[[
-- Havoc (Orca-based), a high-performance Roblox script.
-- This script was generated by ci/bundle.lua, and is not intended to be modified.
--]]

-- Runtime module

---@class Module
---@field fn function
---@field isLoaded boolean
---@field value any

local instanceFromId = {}
local idFromInstance = {}
local modules = {}
local currentlyLoading = {}

-- Module resolution

local function validateRequire(module, caller)
	currentlyLoading[caller] = module
	local currentModule = module
	local depth = 0

	if not modules[module] then
		while currentModule do
			depth = depth + 1
			currentModule = currentlyLoading[currentModule]
			if currentModule == module then
				local str = currentModule.Name
				for _ = 1, depth do
					currentModule = currentlyLoading[currentModule]
					str = str .. "  ⇒ " .. currentModule.Name
				end
				error("Circular dependency detected: " .. str, 2)
			end
		end
	end

	return function ()
		if currentlyLoading[caller] == module then
			currentlyLoading[caller] = nil
		end
	end
end

local function loadModule(obj, this)
	local cleanup = this and validateRequire(obj, this)
	local module = modules[obj]

	if module.isLoaded then
		if cleanup then cleanup() end
		return module.value
	else
		-- Wrap in pcall so we get a better error if a specific file crashes
		local success, result = pcall(module.fn)
		if not success then
			error("\n[!] Failed to load module: " .. obj:GetFullName() .. "\n[!] Error: " .. tostring(result), 0)
		end
		
		module.value = result
		module.isLoaded = true
		if cleanup then cleanup() end
		return result
	end
end

local function requireModuleInternal(target, this)
	if modules[target] and target:IsA("ModuleScript") then
		return loadModule(target, this)
	else
		return require(target)
	end
end

-- Instance creation

local function newEnv(id)
	-- Fallback for executors with restricted environments
	local success, env = pcall(getfenv, 0)
	if not success then env = _G end

	return setmetatable({
		VERSION = __VERSION__,
		script = instanceFromId[id],
		require = function (module)
			return requireModuleInternal(module, instanceFromId[id])
		end,
	}, {
		__index = env,
		__metatable = "This metatable is locked",
	})
end

local function newModule(name, className, path, parent, fn)
	local instance = Instance.new(className)
	instance.Name = name
	instance.Parent = instanceFromId[parent]

	instanceFromId[path] = instance
	idFromInstance[instance] = path

	modules[instance] = {
		fn = fn,
		isLoaded = false,
		value = nil,
	}
end

local function newInstance(name, className, path, parent)
	local instance = Instance.new(className)
	instance.Name = name
	instance.Parent = instanceFromId[parent]

	instanceFromId[path] = instance
	idFromInstance[instance] = path
end

-- Runtime

local function init()
	if not game:IsLoaded() then
		game.Loaded:Wait()
	end
	
	for object in pairs(modules) do
		if object:IsA("LocalScript") and not object.Disabled then
			task.spawn(function()
				local success, err = pcall(loadModule, object)
				if not success then
					warn("[Havoc Runtime Error]: " .. tostring(err))
				end
			end)
		end
	end
end
