--[[
    Havoc Studios Bundler 
	This script was generated by ci/bundle.lua, and is not intended to be modified
--]]

-- 1. Capture Globals Immediately (Fixes "index nil with 'new'")
local Instance = Instance or _G.Instance
local game = game or _G.game
local task = task or _G.task
local require = require or _G.require
local setmetatable = setmetatable or _G.setmetatable
local pcall = pcall or _G.pcall
local error = error or _G.error
local warn = warn or _G.warn

local instanceFromId = {}
local idFromInstance = {}
local modules = {}
local currentlyLoading = {}

-- Module resolution logic
local function validateRequire(module, caller)
    currentlyLoading[caller] = module
    local currentModule = module
    local depth = 0

    if not modules[module] then
        while currentModule do
            depth = depth + 1
            currentModule = currentlyLoading[currentModule]
            if currentModule == module then
                local str = currentModule.Name
                for _ = 1, depth do
                    currentModule = currentlyLoading[currentModule]
                    str = str .. "  ⇒ " .. currentModule.Name
                end
                error("Circular dependency detected: " .. str, 2)
            end
        end
    end

    return function ()
        if currentlyLoading[caller] == module then
            currentlyLoading[caller] = nil
        end
    end
end

local function loadModule(obj, this)
    local cleanup = this and validateRequire(obj, this)
    local module = modules[obj]

    if module.isLoaded then
        if cleanup then cleanup() end
        return module.value
    else
        local success, result = pcall(module.fn)
        if not success then
            error("\n[!] Failed to load module: " .. obj:GetFullName() .. "\n[!] Error: " .. tostring(result), 0)
        end
        
        module.value = result
        module.isLoaded = true
        if cleanup then cleanup() end
        return result
    end
end

local function requireModuleInternal(target, this)
    if modules[target] and target:IsA("ModuleScript") then
        return loadModule(target, this)
    else
        return require(target)
    end
end

-- Instance creation helpers
local function newEnv(id)
    local success, env = pcall(getfenv, 0)
    if not success then env = _G end

    return setmetatable({
        VERSION = __VERSION__,
        script = instanceFromId[id],
        require = function (module)
            return requireModuleInternal(module, instanceFromId[id])
        end,
    }, {
        __index = env,
        __metatable = "This metatable is locked",
    })
end

local function newModule(name, className, path, parent, fn)
    -- Safety check for Instance
    if not Instance then error("[Havoc Runtime Error]: 'Instance' global is nil", 0) end
    
    local instance = Instance.new(className)
    instance.Name = name
    
    -- Safety check for Parent
    if parent and instanceFromId[parent] then
        instance.Parent = instanceFromId[parent]
    end

    instanceFromId[path] = instance
    idFromInstance[instance] = path

    modules[instance] = {
        fn = fn,
        isLoaded = false,
        value = nil,
    }
end

local function newInstance(name, className, path, parent)
    -- Safety check for Instance
    if not Instance then error("[Havoc Runtime Error]: 'Instance' global is nil", 0) end

    local instance = Instance.new(className)
    instance.Name = name
    
    -- Safety check for Parent
    if parent and instanceFromId[parent] then
        instance.Parent = instanceFromId[parent]
    end

    instanceFromId[path] = instance
    idFromInstance[instance] = path
end

-- Initialization
local function init()
    if not game:IsLoaded() then
        game.Loaded:Wait()
    end
    
    for object in pairs(modules) do
        if object:IsA("LocalScript") and not object.Disabled then
            task.spawn(function()
                local success, err = pcall(loadModule, object)
                if not success then
                    warn("[Havoc Runtime Error]: " .. tostring(err))
                end
            end)
        end
    end
end
