--[[
    Havoc Studios Runtime Engine
    This was generated by /bundle.ts and is not meant to be modified.
]]
local instanceFromId, modules = {}, {}
local _G = (getfenv and getfenv()) or _G
local ROOT_PARENT = "ROOT"

local function resolveParent(parentId)
    if parentId == ROOT_PARENT then
        local Players = game:GetService("Players")
        return Players.LocalPlayer:WaitForChild("PlayerGui")
    end
    local parent = instanceFromId[parentId]
    if not parent then
        error(string.format("[Havoc] resolveParent: no instance registered for id '%s'", tostring(parentId)))
    end
    return parent
end

local hEnv

local TS = {
    import = function(self, s, ...)
        local args = {...}
        local last = s
        for i, v in ipairs(args) do
            if type(v) == "string" then
                last = last:FindFirstChild(v)
            else
                last = v
            end
        end
        if modules[last] then
            local m = modules[last]
            if not m.loaded then
                m.loaded = true
                local innerFunc = m.fn()
                setfenv(innerFunc, hEnv(last:GetFullName()))
                m.data = innerFunc()
            end
            return m.data
        end
        return require(last)
    end,
    getModule = function(self, s, ...)
        return _G.require(s)
    end
}

hEnv = function(id)
    local inst = instanceFromId[id]
    local env = setmetatable({
        script = inst,
        require = function(target)
            if modules[target] then
                local m = modules[target]
                if not m.loaded then
                    m.loaded = true
                    local innerFunc = m.fn()
                    setfenv(innerFunc, hEnv(target:GetFullName()))
                    m.data = innerFunc()
                end
                return m.data
            end
            return require(target)
        end
    }, { __index = _G })
    _G[inst] = TS
    return env
end

local function hMod(name, class, id, parentId, fn)
    local ok, inst = pcall(Instance.new, class)
    if not ok then
        warn(string.format("[Havoc] Skipping hMod for %s (%s) — not instantiable", name, class))
        return
    end
    inst.Name = name
    inst.Parent = resolveParent(parentId)
    instanceFromId[id] = inst
    modules[inst] = { fn = fn, loaded = false }
end

local function hInst(name, class, id, parentId)
    local ok, inst = pcall(Instance.new, class)
    if not ok then
        warn(string.format("[Havoc] Skipping hInst for %s (%s) — not instantiable", name, class))
        return
    end
    inst.Name = name
    inst.Parent = resolveParent(parentId)
    instanceFromId[id] = inst
end

local function hInit()
    for inst, m in pairs(modules) do
        if inst:IsA("LocalScript") then
            task.spawn(function()
                local fn = m.fn()
                setfenv(fn, hEnv(inst:GetFullName()))
                fn()
            end)
        end
    end
end

return hInit, hMod, hInst, hEnv
