name: Publish Release
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'ci/**'
jobs:
  bundle-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Rojo/Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install NPM dependencies
        run: npm install
      - name: Build
        run: |
          npm run compile
          npm run build
      - name: Bundle modules
        run: |
          remodel run ci/bundle.lua Havoc.rbxm public/latest.lua minify
          remodel run ci/bundle.lua Havoc.rbxm public/latest.debug.lua debug
      - name: Commit latest builds
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "public/latest.lua public/latest.debug.lua Havoc.rbxm"
          message: "🔥 Release build ${{ github.run_id }} - Auto-build from src"
          push: '--force'
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          tag_name: latest
          name: Latest Release
          body: |
            **Auto-built** from commit ${{ github.sha }}
          draft: false
          prerelease: false
          files: |
            public/latest.lua
            public/latest.debug.lua
            Havoc.rbxm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
